[workspace]
members = ["crates/problems", "crates/problems-derive"]
resolver = "3"

[workspace.package]
license = "MIT"

[workspace.dependencies]
actix-web = { version = "4.15.0", default-features = false }
aide = { version = "0.15.1", default-features = false }
axum = "0.8.9"
heck = "0.5.0"
http = "1.5.0"
poem = { version = "3.1.12", default-features = false }
problems-derive = { version = "0.1.0", path = "crates/problems-derive" }
proc-macro-crate = "3.5.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
rocket = { version = "0.5.1", default-features = false }
salvo = { version = "1.0.0", default-features = false }
schemars = "1.2.2"
serde = "1.0.229"
serde_json = "1.0.151"
syn = "3.0.6"
thiserror = "2.0.21"
tokio = "1.53.2"
tower = "0.5.3"
warp = { version = "0.4.3", default-features = false }
