[package]
name = "problems-example-poem"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false
description = "A Poem application demonstrating typed HTTP problems."

[dependencies]
problems = { path = "../../crates/problems", features = ["poem"] }
poem = { workspace = true, features = ["server"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net"] }

[dev-dependencies]
hurl-test = "0.2.0"
miette = { version = "7.6.0", features = ["fancy"] }
