[package]
name = "problems-example-actix-web"
version = "0.1.0"
edition = "2024"
license.workspace = true
publish = false
description = "An Actix Web application demonstrating typed HTTP problems."

[dependencies]
problems = { path = "../../crates/problems", features = ["actix-web"] }
actix-web = { workspace = true, features = ["macros"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net"] }

[dev-dependencies]
hurl-test = "0.2.0"
miette = { version = "7.6.0", features = ["fancy"] }
